### ISSUE TITLE
[mieb] Winoground not working

### ISSUE THREAD

**Issue by Muennighoff** [embeddings-benchmark/mteb#1383]
```
ERROR:mteb.evaluation.MTEB:Error while evaluating Winoground: DatasetInfo.__init__() got an unexpected keyword argument 'task_templates'
Traceback (most recent call last):
  File "/data/niklas/mieb/mteb/scripts/run_mieb.py", line 81, in <module>
    results = evaluation.run(model, output_folder="/data/niklas/mieb/results-mieb-final", batch_size=1)
  File "/data/niklas/mieb/mteb/mteb/evaluation/MTEB.py", line 464, in run
    raise e
  File "/data/niklas/mieb/mteb/mteb/evaluation/MTEB.py", line 394, in run
    task.load_data(eval_splits=task_eval_splits, **kwargs)
  File "/data/niklas/mieb/mteb/mteb/abstasks/AbsTask.py", line 192, in load_data
    self.dataset = datasets.load_dataset(**self.metadata_dict["dataset"])  # type: ignore
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/datasets/builder.py", line 353, in __init__
    info.update(self._info())
  File "/data/huggingface/modules/datasets_modules/datasets/facebook--winoground/72585f4d9cd5a28790bb9bc2adbdd45633f36dfbf85df529e0756e114e134285/winoground.py", line 61, in _info
    return datasets.DatasetInfo(
TypeError: DatasetInfo.__init__() got an unexpected keyword argument 'task_templates'

```

**Comment by gowitheflow-1998** [comment]
could be relevant to `datasets` version like #1381 as well. I updated to `3.0.2` and was able to reproduce the error. The current dataset version works with 2.19.0 and 2.20.0.
Seems like Winoground has recently removed their loading script on HF and turned into parquet; so now `datasets==3.0.2` works with a dataset revision id "b400e173549071916ad1b3d449293bc8d8b4b763" as well

**Comment by Muennighoff** [comment]
Getting the below issue with Winoground & `royokong/e5-v` now
```
ERROR:mteb.evaluation.MTEB:Error while evaluating Winoground: 'NoneType' object has no attribute 'dtype'
Traceback (most recent call last):
  File "/data/niklas/mieb/mteb/scripts/run_mieb.py", line 90, in <module>
    results = evaluation.run(model, output_folder="/data/niklas/mieb/results-mieb-final", batch_size=16)
  File "/data/niklas/mieb/mteb/mteb/evaluation/MTEB.py", line 464, in run
    raise e
  File "/data/niklas/mieb/mteb/mteb/evaluation/MTEB.py", line 425, in run
    results, tick, tock = self._run_eval(
  File "/data/niklas/mieb/mteb/mteb/evaluation/MTEB.py", line 300, in _run_eval
    results = task.evaluate(
  File "/data/niklas/mieb/mteb/mteb/abstasks/AbsTask.py", line 126, in evaluate
    scores[hf_subset] = self._evaluate_subset(
  File "/data/niklas/mieb/mteb/mteb/abstasks/Image/AbsTaskImageTextPairClassification.py", line 56, in _evaluate_subset
    scores = evaluator(model, encode_kwargs=encode_kwargs)
  File "/data/niklas/mieb/mteb/mteb/evaluation/evaluators/Image/ImageTextPairClassificationEvaluator.py", line 141, in __call__
    model.get_text_embeddings(texts, batch_size=len(texts)),
  File "/data/niklas/mieb/mteb/mteb/models/e5_v.py", line 56, in get_text_embeddings
    text_outputs = self.model(
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/transformers/models/llava_next/modeling_llava_next.py", line 874, in forward
    inputs_embeds = inputs_embeds.to(image_features.dtype)
AttributeError: 'NoneType' object has no attribute 'dtype'
```

**Comment by isaac-chung** [comment]
- e5v transformers version check https://github.com/embeddings-benchmark/mteb/pull/1723
- winoground has results for e5v: https://github.com/embeddings-benchmark/tmp/blob/master/royokong__e5-v/0c1f22679417b3ae925d779442221c40cd1861ab/Winoground.json
