### ISSUE TITLE
MTEB compatibility with newer vllm versions

### ISSUE THREAD

**Issue by Lossfull** [embeddings-benchmark/mteb#4379]
### Describe the bug

In newer vllm versions truncate_prompt_tokens was moved to PoolingParams and when using vllmencoderwrapper with mteb and newer versions of vllm, it throws an error

TypeError: LLM.encode() got an unexpected keyword argument 'truncate_prompt_tokens'

https://github.com/vllm-project/vllm/pull/31013

### To reproduce

to reproduct just install mteb with vllm (uv pip install "mteb[vllm]") and try to run example code for vllmwrapper from mteb documentation

```py
import mteb
from mteb.models.vllm_wrapper import VllmEncoderWrapper

def run_vllm_encoder():
    """Evaluate a model on specified MTEB tasks using vLLM for inference."""
    encoder = VllmEncoderWrapper(model="intfloat/e5-small")
    return mteb.evaluate(
        encoder,
        mteb.get_task("STS12"),
    )

if __name__ == "__main__":
    results = run_vllm_encoder()
    print(results)
```

### Are you interested to contribute a fix for this bug?

No

**Comment by Lossfull** [comment]
actually even moving truncate_prompt_tokens to poolingparams doesn't work because poolingparams does not have this argument anymore, investigating further on ways to fix this

**Comment by Lossfull** [comment]
i was able to fix vllmwrapper to work with latest vllm 0.19.0 by moving truncate_prompt_tokens to tokenization_kwargs and then passing it to encode method. Looks like this is current expected approach for vllm

tokenization_kwargs = {"truncate_prompt_tokens":-1}
outputs = self.llm.encode(prompts, pooling_task="embed", tokenization_kwargs=tokenization_kwargs)

**Comment by Samoed** [comment]
Can you submit pr with fix?
